% date_string='_feb22'; %if you want to add a different date to the filename, put it here
%
%
[sportmat_oddsonly_live0, sportodds_live0,  sportou_live0, sportoddpl_live0, datelist_live0, date1_pl_live0, ...
   date1_offshore_live0, sportmatc_oddsonlyOS_live0, sportoddsOS_live0, sportouOS_live0, sportoddplOS_live0, ...
   booknameodds, booknameoddsOS, booknameou, booknameouOS, bookname_pl, bookname_plOS, gamenotes0, ...
  sportmatc_oddsonly_pl, sportmatc_oddsonly_plOS ] = nhllv_scrape(date_string);